### ISSUE TITLE
duplicated updates with french UI

### ISSUE THREAD

**Issue by troublestarter** [amidaware/tacticalrmm#647]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Edge
 - RMM Version (as shown in top left of web UI): v0.7.2

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information): 
Red Hat KVM
Intel Xeon Processor (Skylake, IBRS)
6 GB RAM
Red Hat VirtIO SCSI Disk Device 37GB SCSI
Microsoft Basic Display Adapter
- Agent OS: Windows Server 2019 Standard, 64 bit v1809 (build 17763.2090) • Agent v1.5.9 **FRENCH RELEASE**

**Describe the bug**
Duplicated updates appears

**To Reproduce**
No

**Expected behavior**
Just have a single update

**Screenshots**
![image](https://user-images.githubusercontent.com/6012203/126564880-447bbef3-a52c-401f-ba0c-7b276183c554.png)

![image](https://user-images.githubusercontent.com/6012203/126564890-5f1e9bb3-a2ac-4ec7-bfa4-d9ef49ac3ed6.png)

**Additional context**
French release

**Comment by troublestarter** [comment]
edit this file on your server /rmm/api/tacticalrmm/agents/models.py
line 775 re.search(r"\(Version(.*?)\)", i).group(1).strip()
change to re.search(r"\(version(.*?)\)", i).group(1).strip()
Version change the V to lowercase version

Done, problem solve for that particular update.

Still having the problem for that one :
![image](https://user-images.githubusercontent.com/6012203/126567739-03b60566-67b4-437b-a5ca-f88058ca02fc.png)

![image](https://user-images.githubusercontent.com/6012203/126567746-d5b1e114-7890-494e-aae2-4b1a34469943.png)

**Comment by WaffleBoyQc** [comment]
Server Info (please complete the following information):

OS: Ubuntu 20.04
Browser: Chrome
RMM Version (as shown in top left of web UI): v0.15.8
Installation Method:

 Standard
SSH script


Agent OS: Windows 10 21H2
Describe the bug
Duplicated updates appears

To Reproduce
No

Expected behavior
Just have a single update

Screenshots

![image](https://user-images.githubusercontent.com/100486259/229842954-3b478261-b4c8-444a-968c-f3a8a27f25a0.png)

**Comment by wh1te909** [comment]
fixed in latest release
