### ISSUE TITLE
Patch Management - Lost the Patches Last Installed Date

### ISSUE THREAD

**Issue by silversword411** [amidaware/tacticalrmm#787]
**Server Info (please complete the following information):**
 - RMM Version (as shown in top left of web UI): 0.9.0

Have buttons for Patch Management now, but patches last installed date is gone.

**Comment by silversword411** [comment]
![2021-11-07_102557 - TRMM patches last installed date](https://user-images.githubusercontent.com/13395348/140651305-6a3dbb9d-02f4-4b39-a7ad-d6d02c136534.png)

**Comment by sadnub** [comment]
I actually removed that because it was causing confusion. The last_patches date is meant to track tactical auto patching policies and won't update when patches are manually installed. We can revisit this though. Patching is one of those things that need to be overhauled at the moment, so I am betting there will be some new DB fields to display in the UI

**Comment by silversword411** [comment]
I think this is no longer applicable
