### ISSUE TITLE
IP and FQDN Whitelisting

### ISSUE THREAD

**Issue by asasin114** [amidaware/tacticalrmm#917]
It would be super handy to have a whitelist with the ability to add IP addresses and FQDN's that allow agent communication and interface access for an additional layer of security. I'm super impressed with the security that has already been used out of the box and I think this would be a fantastic addition to that stack. Obviously I can do this with firewall rules on a gateway placed in front of the TacticalRMM installation and I do use that functionality but having it baked into the suite itself would take things to another level.

**Comment by dinger1986** [comment]
currently you can do it with ufw as well, but shall leave it open incase the devs want to control this from the ui

**Comment by bc24fl** [comment]
> 

If this was "baked" into the suite how would you handle those agents on a DHCP static address?

**Comment by asasin114** [comment]
That's where the FQDN comes in. If you have a dynamic DNS setup with a DHCP address then whitelisting the FQDN will ensure the DHCP address is covered in most situations.

Taylor Bornyk
CTO - Insight Hosting
Direct: 306-500-9150 Office: 306-500-0234
________________________________

**Comment by bc24fl** [comment]
What are your thoughts on addressing remote users with laptops?

**Comment by asasin114** [comment]
Those users will be using a VPN to direct their traffic through the office when on the road so they will communicate back to Tactical through that.

Taylor Bornyk
CTO - Insight Hosting
Direct: 306-500-9150 Office: 306-500-0234
________________________________

**Comment by bc24fl** [comment]
And if they can't get on VPN or their VPN isn't configured to route all their traffic as common across many organizations, or you just need unattended access?  I'm asking these questions because I'm also looking for a solution to that problem but I don't think Tactical can handle it correctly.  This would be a good discussion to have with the Tactical discord community to get more ideas.

**Comment by silversword411** [comment]
VPN
SDN
DDNS
Port Knock

These are the general techniques I know about, add any others you can think of.

**Comment by bc24fl** [comment]
I’ve contemplated doing the whole private network thing using vpn/sdn but I just don’t feel comfortable having all my managed client computers part of essentially the same network.   It’s my understanding from conversations with others however that you can isolate segments (ie: companies) from each other.  One such tool that may work is Nebula but I haven’t yet done enough research to know for sure and how secure it really is.  

So as a temporary solution I began developing an in house solution that essentially runs an agent on each client that authenticates with a light web service which  whitelists Ips/Ports on the servers I need open.  Then every night it flushes out all the dynamic Ips it added the day prior.  Since my servers are generally housed in one of the major cloud providers, I can use their API’s to easily do this on their provided virtual firewalls (In AWS it’s a Security Group).  Sounds hackish, maybe, but it’s better than having all my servers exposed to 0.0.0.0/0 .   Thoughts?

**Comment by NiceGuyIT** [comment]
First, I do not think TRMM should manage the architecture for your systems. You'll get into the chicken-or-the-egg scenario where TRMM is managing the network to allow clients into the network so they can be managed by TRMM.

----

There are two parts: on-boarding and maintenance.

The maintenance is relatively simple because you already authenticated the agent. Maintenance involves rotating certificates, rotating credentials, revoking access, etc.

On-boarding is the hard part because any program you run to give access to your system could be run by an unknown party to gain access. Example from the [docs](https://wh1te909.github.io/tacticalrmm/faq/#help-ive-been-hacked-there-are-weird-agents-appearing-in-my-tactical-rmm). I'm specifically talking about "always on" or automated systems, not systems where the user has to login. What happens if a user can't login to VPN and you need to access their computer to assist? Back to chicken-or-the-egg scenario.

I see two main paths:

1. Manually onboard the asset. This option does not scale well for obvious reasons but may be acceptable for small shops. The usual option is to use a certificate 
2. On-boarded assets are sent to a "queue" to be manually approved. Once approved, the asset will have access.

I'm working through the details of implementing Nebula (SDN or always-on VPN) as my gatekeeper. Authentication is made via TLS cert. Revoking the cert kicks the computer out of the network. Assets don't talk to each other unless you specifically open the firewall ports in Nebula **and** the assets have the same CA (technically not true but good enough for this explanation). The ongoing maintenance is simple if you add a long expiration, say 10 years. A shorter lifespan would require some sort of management/automation. On-boarding is the tricky part. Since it's not rolled out yet (Nebula is used only internally), I'm holding off until I can work through path 2: on-boarding to a queue with manual approval.

Initially I thought [firewalld-rest](https://github.com/prashantgupta24/firewalld-rest) would help with the on-boarding, but after looking at the implementation, it won't work without some modification. Another option I've thought about is a TRMM style NATS setup where the client authentication is done with TLS certs and NATS is exposed to the world (or to your part of the world). The required footprint will be smaller and learning NATS will help with TRMM.

**Comment by sadnub** [comment]
IP addresses can be whitelisted in the nginx configuration. This is probably the best option since it whitelists based on the connection ip address. 

Address detection back to backend or dashboard apps will be very unreliable and we need to check HTTP headers to try and make the best guess at what the client ip address is.
